import sbms
Import('*')

subdirs = [
'MilleFieldOff',
'MilleFieldOn'
]

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets
optdirs = [
'FDC_InternalAlignment',
'MilleKs',
'FDCProjectionResiduals'
]

sbms.OptionallyBuild(env, optdirs)
