

Import('*')

#subdirs = ['hd_ana', 'hd_root', 'hd_dump', 'hd_eventfilter', 'hdview2']
subdirs = ['hd_ana', 'hd_root', 'hd_dump', 'hd_eventfilter'] # TODO: NWB: Re-enable hdview2

SConscript(dirs=subdirs, exports='env osname', duplicate=0)
