// plots values in ampzero2.txt generated by plotampratio.C

{

  const int maxnd=540;
  float run[maxnd],dmax[maxnd],xzero[maxnd],xd[maxnd],nlate[maxnd];

  FILE *inf = fopen("ampzero2.txt","r");

  int i=0;
  int itemp,itemp2;
  float ftemp, ftemp2;

  while (!feof(inf)) {
    //40856 0.650 1.050 0.400 0.098 0.748 20

    fscanf(inf,"%i %f %f %f %*f %*f %i" ,&itemp, &dmax[i], &xzero[i], &xd[i], &itemp2);

    if (feof(inf)) break;

    run[i] = (float)itemp;
    nlate[i] = (float)itemp2;

    i++;
  }

  fclose(inf);

  const int nd = i;

  cout << nd << endl;

  i=nd-1;
  //  printf("%f %f %f %f %f\n",run[i],dmax[i],xzero[i],xd[i],nlate[i]);

  gStyle->SetOptStat("me");
  gStyle->SetTitleOffset(1.2,"Y");
  gStyle->SetTitleOffset(1.1,"X");

  TGraph *g = new TGraph(nd,dmax,xd);
  g->SetTitle("Distance between dE/dx cutoff and DOCA where pulse height MPV=0;dE/dx cutoff DOCA (cm);DOCA where pulse height MPV=0 - dmax (cm)");
  g->SetMarkerStyle(20);
  g->SetMarkerSize(0.4);
  g->GetXaxis()->SetRangeUser(0,0.6);
  g->Draw("AP");

  new TCanvas;
  TGraph *g2 = new TGraph(nd,run,xd);
  g2->SetTitle("Distance between dE/dx cutoff and DOCA where pulse height MPV=0;run;DOCA where pulse height MPV=0 - dmax (cm)");
  g2->SetMarkerStyle(20);
  g2->SetMarkerSize(0.4);
  g2->Draw("AP");
 
  gStyle->SetOptStat(110);
  new TCanvas;
  TH1D *h2 = new TH1D("h2","Distance between dE/dx cutoff and DOCA where pulse height MPV=0;DOCA where pulse height MPV=0 - dmax (cm)",200,0.1,0.5); 

  for (i=0;i<nd;i++) h2->Fill(xd[i]);

  h2->Draw();

  new TCanvas;



  TH1D *h3 = new TH1D("h3","Distance between dE/dx cutoff and DOCA where pulse height MPV=0 (dmax 0.45 to 0.6cm);DOCA where pulse height MPV=0 - dmax (cm)",200,0.1,0.5); 

  for (i=0;i<nd;i++) if (dmax[i]>0.44 && dmax[i]<=0.6) h3->Fill(xd[i]);
  h3->Draw();



  // mean is 0.33, st dev is 0.03


  new TCanvas;



  TH1D *h33 = new TH1D("h33","Distance between dE/dx cutoff and DOCA where pulse height MPV=0 (dmax < 0.6cm);DOCA where pulse height MPV=0 - dmax (cm)",200,0.1,0.5); 

  for (i=0;i<nd;i++) if (dmax[i]<=0.6) h33->Fill(xd[i]);
  h33->Draw();


  

  new TCanvas;






  TH2D *h = new TH2D("h","Distance between dE/dx cutoff and DOCA where pulse height MPV=0;max DOCA used for dE/dx (cm);DOCA where pulse height MPV=0 - dmax (cm)",26,0.4,0.67,200,0.1,0.5); 

  for (i=0;i<nd;i++) h->Fill(dmax[i],xd[i]);
  h->Draw("colz");


  for (i=0;i<nd;i++) if (fabs(xd[i]-0.33)>0.09) cout << run[i] << " " << xd[i] << " " << nlate[i] << endl;




  new TCanvas;
  TH2D *h4 = new TH2D("h4","Extra radius beyond dE/dx cutoff with hit mpv>0;nlate",200,0.1,0.5,20,0,20); 

  for (i=0;i<nd;i++) h4->Fill(xd[i],nlate[i]);
  h4->Draw("colz");

}
