
import sbms

Import('*')

# Default targets (always built)
subdirs = ['1p2pi']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)


# Optional targets
optdirs = []

sbms.OptionallyBuild(env, optdirs)

