import sbms
Import('*')

subdirs = [
'occupancy_online',
'lowlevel_online',
'BCAL_online',
'CCAL_online',
'CDC_dedx',
'CDC_online',
'DAQ_online',
'fa125_itrig',
'FCAL_online',
'FCAL_invmass',
'FDC_online',
'FDC_Efficiency',
'FMWPC_online',
'FMWPC_Performance',
'PSC_online',
'RF_online',
'PS_online',
'PSPair_online',
'PS_flux',
'ST_online_lowlevel',
'TAGGER_online',
'TAGH_online',
'TAGM_online',
'TAGM_clusters',
'TOF_online',
'TRIG_online',
'TPOL_online',
'CDC_expert_2',
'TOF_TDC_shift',
'BCAL_Eff',
'BCAL_inv_mass',
'CDC_drift',
'CDC_Efficiency',
'L1_online',
'highlevel_online',
'BCAL_Hadronic_Eff',
'FCAL_Hadronic_Eff',
'TrackingPulls',
'DIRC_online',
'BEAM_online',
'lumi_mon',
'HELI_online' 
]


optdirs = ['TAGH_doubles','ST_ZEff', 'CODA_online', 'EVNT_online']
optdirs.extend(['BCAL_LED_time', 'BCAL_LED', 'FCAL_cpp', 'pedestal_online', 'CDC_PerStrawReco','CDC_roc_hits' ])
optdirs.extend(['EPICS_dump', 'SC_Eff','TOF_Eff', 'TS_scaler', 'TrackingPulls_straight', 'timing_online', 'TRD_online' ])
optdirs.extend(['RSAI_KO', 'scaler_primex', 'cppFMWPC', 'cppFMWPC_ana', 'cpp_itrig', 'primex-online' ])
sbms.OptionallyBuild(env, optdirs)

SConscript(dirs=subdirs, exports='env osname', duplicate=0)
