// $Id$
//

/*! **File**: DCTOFDigiHit.h
 *+ Created: Thu 05 May 2022 10:15:51 AM EDT
 *+ Creator: Beni
 *+ Purpose: Container class object holding raw fADC250 data: integral, pulse, pedestal, time
 */

/// \defgroup CTOFDetector CTOF Detector Objects

#ifndef _DCTOFDigiHit_
#define _DCTOFDigiHit_

#include <JANA/JObject.h>


/*! \file DCTOFDigiHit.h 
 * container class hodling raw fADC250 DATA for CTOF hits.
 */



// the follwing is for doxygen describing the class
/*! \class DCTOFDigiHit 
 * This is a container class holding raw data from CTOF fADC250s
 * The data is generated by the algorithm running on the FPGAs of the ADC modules
 * and converted to uint32_t values for this container class by the data reader/translator code.
 */
class DCTOFDigiHit:public JObject{
 public:
  JOBJECT_PUBLIC(DCTOFDigiHit);
  
  int plane;   ///<  (0: vertical)
  int bar;     ///< paddle number: 1, 2, 3, 4)
  int end;     ///< North/South 0/1 (same as left/right) looking in beam direction, TOP/BOTTIOM 0/1
  uint32_t pulse_integral; ///< identified pulse integral as returned by FPGA algorithm
  uint32_t pulse_time;     ///< identified pulse time as returned by FPGA algorithm
  uint32_t pedestal;       ///< pedestal info used by FPGA (if any)
  uint32_t QF;             ///<  Quality Factor from FPGA algorithms
  uint32_t nsamples_integral;    ///<  number of samples used in integral 
  uint32_t nsamples_pedestal;    ///< number of samples used in pedestal
  uint32_t pulse_peak;           ///<  maximum ADC value in pulse peak (pedestal is NOT subtracted)
  
  uint32_t datasource;           ///<  0=window raw data, 1=old(pre-Fall16) firmware, 2=Df250PulseData
  
  // This method is used primarily for pretty printing
  void Summarize(JObjectSummary& summary) const override { 
    summary.add(bar, "bar", "%d");
    summary.add(plane, "plane", "%d");
    summary.add(end, "end", "%d");
    summary.add(pulse_integral, "pulse_integral", "%d");
    summary.add(pulse_peak, "pulse_peak", "%d");
    summary.add(pulse_time, "pulse_time", "%d");
    summary.add(pedestal, "pedestal", "%d");
    summary.add(QF, "QF", "%d");
    summary.add(nsamples_integral, "nsamples_integral", "%d");
    summary.add(nsamples_pedestal, "nsamples_pedestal", "%d");
  }
  
};

#endif // _DCTOFDigiHit_

