// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.36/04       [402436]
Creator        : apollo
Date           : Mon Mar  2 10:03:08 2026
Host           : Darwin Mac-1759393079197.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64 x86_64
Dir            : /Users/apollo/Work/cpp_analysis/ml_models/project_hylax/root_tmva/single_track_tmva/plustrack
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
FCAL_eoverp_8                 FCAL_eoverp_8                 FCAL_eoverp_8                 FCAL_eoverp_8                                                   'F'    [0,1.13870537281]
FCAL_doca_8                   FCAL_doca_8                   FCAL_doca_8                   FCAL_doca_8                                                     'F'    [0.00257715024054,999]
FCALShower_E1E9_8             FCALShower_E1E9_8             FCALShower_E1E9_8             FCALShower_E1E9_8                                               'F'    [0,1]
FCAL_blocks_n_8               FCAL_blocks_n_8               FCAL_blocks_n_8               FCAL_blocks_n_8                                                 'F'    [0,15]
Chamber1MatchedHits8          Chamber1MatchedHits8          Chamber1MatchedHits8          Chamber1MatchedHits8                                            'F'    [0,45]
Chamber2MatchedHits8          Chamber2MatchedHits8          Chamber2MatchedHits8          Chamber2MatchedHits8                                            'F'    [0,32]
Chamber3MatchedHits8          Chamber3MatchedHits8          Chamber3MatchedHits8          Chamber3MatchedHits8                                            'F'    [0,34]
Chamber4MatchedHits8          Chamber4MatchedHits8          Chamber4MatchedHits8          Chamber4MatchedHits8                                            'F'    [0,21]
Chamber5MatchedHits8          Chamber5MatchedHits8          Chamber5MatchedHits8          Chamber5MatchedHits8                                            'F'    [0,19]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_PIMU_Plus : public IClassifierReader {

 public:

   // constructor
   ReadMLP_PIMU_Plus( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP_PIMU_Plus" ),
        fNvars( 9 )
   {
      // the training input variables
      const char* inputVars[] = { "FCAL_eoverp_8", "FCAL_doca_8", "FCALShower_E1E9_8", "FCAL_blocks_n_8", "Chamber1MatchedHits8", "Chamber2MatchedHits8", "Chamber3MatchedHits8", "Chamber4MatchedHits8", "Chamber5MatchedHits8" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_PIMU_Plus() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][9];
   double fScal_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[15][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

};

inline void ReadMLP_PIMU_Plus::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.181320914600535;
   fWeightMatrix0to1[1][0] = 1.99069582582932;
   fWeightMatrix0to1[2][0] = 1.10682771030927;
   fWeightMatrix0to1[3][0] = 2.44735308077662;
   fWeightMatrix0to1[4][0] = -0.243578833679595;
   fWeightMatrix0to1[5][0] = -0.877721497879067;
   fWeightMatrix0to1[6][0] = -0.780902684764915;
   fWeightMatrix0to1[7][0] = 2.14269164835518;
   fWeightMatrix0to1[8][0] = -1.74021532299015;
   fWeightMatrix0to1[9][0] = -0.697941658878603;
   fWeightMatrix0to1[10][0] = -1.25135228921938;
   fWeightMatrix0to1[11][0] = -0.684532872029843;
   fWeightMatrix0to1[12][0] = -1.54765954154316;
   fWeightMatrix0to1[13][0] = -0.449591148939676;
   fWeightMatrix0to1[0][1] = 0.525586451455257;
   fWeightMatrix0to1[1][1] = 0.900325548418949;
   fWeightMatrix0to1[2][1] = 0.00918104306725489;
   fWeightMatrix0to1[3][1] = 0.892010788247608;
   fWeightMatrix0to1[4][1] = -0.871451184218301;
   fWeightMatrix0to1[5][1] = 5.60784085416274;
   fWeightMatrix0to1[6][1] = -0.683155136088493;
   fWeightMatrix0to1[7][1] = -0.704634174920725;
   fWeightMatrix0to1[8][1] = 1.13157752953997;
   fWeightMatrix0to1[9][1] = -0.483904720392846;
   fWeightMatrix0to1[10][1] = -1.45461706784265;
   fWeightMatrix0to1[11][1] = -0.518106963356534;
   fWeightMatrix0to1[12][1] = 0.713887807894731;
   fWeightMatrix0to1[13][1] = -1.08439948567104;
   fWeightMatrix0to1[0][2] = -0.06682062332522;
   fWeightMatrix0to1[1][2] = 0.0272531387591729;
   fWeightMatrix0to1[2][2] = 0.495529248168976;
   fWeightMatrix0to1[3][2] = 0.70821757817434;
   fWeightMatrix0to1[4][2] = 0.150303013938393;
   fWeightMatrix0to1[5][2] = 0.141117058961536;
   fWeightMatrix0to1[6][2] = 0.506912057846113;
   fWeightMatrix0to1[7][2] = -0.239161045632856;
   fWeightMatrix0to1[8][2] = -2.40706344919533;
   fWeightMatrix0to1[9][2] = 2.58840725232194;
   fWeightMatrix0to1[10][2] = -0.853202458708089;
   fWeightMatrix0to1[11][2] = 0.96566824992503;
   fWeightMatrix0to1[12][2] = 1.17377318415761;
   fWeightMatrix0to1[13][2] = 0.863124784550865;
   fWeightMatrix0to1[0][3] = 0.601595386800739;
   fWeightMatrix0to1[1][3] = 1.7589796198072;
   fWeightMatrix0to1[2][3] = -0.527473215052421;
   fWeightMatrix0to1[3][3] = -0.317695162807918;
   fWeightMatrix0to1[4][3] = -0.0254751365203003;
   fWeightMatrix0to1[5][3] = 0.565949078412681;
   fWeightMatrix0to1[6][3] = 1.56860667869714;
   fWeightMatrix0to1[7][3] = 1.42787188961352;
   fWeightMatrix0to1[8][3] = 1.27976057690045;
   fWeightMatrix0to1[9][3] = 1.72233610041413;
   fWeightMatrix0to1[10][3] = -2.09077092225818;
   fWeightMatrix0to1[11][3] = 1.19941349360282;
   fWeightMatrix0to1[12][3] = -1.76774304518158;
   fWeightMatrix0to1[13][3] = -0.907619155638054;
   fWeightMatrix0to1[0][4] = 0.17208875928106;
   fWeightMatrix0to1[1][4] = -1.56364580213311;
   fWeightMatrix0to1[2][4] = 1.70290228859921;
   fWeightMatrix0to1[3][4] = 0.349827799308275;
   fWeightMatrix0to1[4][4] = -2.84932144481898;
   fWeightMatrix0to1[5][4] = 2.03785116709048;
   fWeightMatrix0to1[6][4] = -0.330480549384743;
   fWeightMatrix0to1[7][4] = 0.716295360990572;
   fWeightMatrix0to1[8][4] = 1.66119395168797;
   fWeightMatrix0to1[9][4] = -0.248944959579077;
   fWeightMatrix0to1[10][4] = 0.888723701988025;
   fWeightMatrix0to1[11][4] = -1.50424164130447;
   fWeightMatrix0to1[12][4] = -0.00648217447678949;
   fWeightMatrix0to1[13][4] = -0.843616573377844;
   fWeightMatrix0to1[0][5] = 1.38842183447114;
   fWeightMatrix0to1[1][5] = -1.30728271879275;
   fWeightMatrix0to1[2][5] = 1.02978942738322;
   fWeightMatrix0to1[3][5] = 0.554433513108585;
   fWeightMatrix0to1[4][5] = 0.209152544029876;
   fWeightMatrix0to1[5][5] = 0.0622384621880684;
   fWeightMatrix0to1[6][5] = -1.76120568071313;
   fWeightMatrix0to1[7][5] = -1.84771012505113;
   fWeightMatrix0to1[8][5] = 0.989015161414299;
   fWeightMatrix0to1[9][5] = 0.461650536343778;
   fWeightMatrix0to1[10][5] = 3.35815471197328;
   fWeightMatrix0to1[11][5] = 0.417519614192447;
   fWeightMatrix0to1[12][5] = 0.278839644566391;
   fWeightMatrix0to1[13][5] = -0.807520661389818;
   fWeightMatrix0to1[0][6] = -0.6800980067125;
   fWeightMatrix0to1[1][6] = 0.0292847404445849;
   fWeightMatrix0to1[2][6] = 1.47465736442203;
   fWeightMatrix0to1[3][6] = -1.78400329841682;
   fWeightMatrix0to1[4][6] = -1.96432621379076;
   fWeightMatrix0to1[5][6] = -4.16854857274014;
   fWeightMatrix0to1[6][6] = -0.279630794868528;
   fWeightMatrix0to1[7][6] = -0.0340393329433456;
   fWeightMatrix0to1[8][6] = 1.63588401730801;
   fWeightMatrix0to1[9][6] = -1.08229485525812;
   fWeightMatrix0to1[10][6] = -0.245280201062598;
   fWeightMatrix0to1[11][6] = 1.51766186825505;
   fWeightMatrix0to1[12][6] = -1.40965180226105;
   fWeightMatrix0to1[13][6] = -1.51926659871416;
   fWeightMatrix0to1[0][7] = -9.24413858792028;
   fWeightMatrix0to1[1][7] = 0.353183171748992;
   fWeightMatrix0to1[2][7] = -1.45716388351097;
   fWeightMatrix0to1[3][7] = -4.09593680255753;
   fWeightMatrix0to1[4][7] = 5.25974473256911;
   fWeightMatrix0to1[5][7] = 0.24118001485373;
   fWeightMatrix0to1[6][7] = -1.07252508236549;
   fWeightMatrix0to1[7][7] = 1.6836719343976;
   fWeightMatrix0to1[8][7] = -0.77992971633245;
   fWeightMatrix0to1[9][7] = -0.957496809917981;
   fWeightMatrix0to1[10][7] = 0.580758384801993;
   fWeightMatrix0to1[11][7] = 0.0733074177913402;
   fWeightMatrix0to1[12][7] = -2.18276847800308;
   fWeightMatrix0to1[13][7] = 0.261576569072227;
   fWeightMatrix0to1[0][8] = 1.26948287949724;
   fWeightMatrix0to1[1][8] = 0.856468512813277;
   fWeightMatrix0to1[2][8] = -0.916758122753427;
   fWeightMatrix0to1[3][8] = 3.72295434617027;
   fWeightMatrix0to1[4][8] = 4.73144677245346;
   fWeightMatrix0to1[5][8] = -9.25446211505484;
   fWeightMatrix0to1[6][8] = 0.66853216983597;
   fWeightMatrix0to1[7][8] = -1.04375720565094;
   fWeightMatrix0to1[8][8] = -1.56680209388301;
   fWeightMatrix0to1[9][8] = 0.0240818042840928;
   fWeightMatrix0to1[10][8] = 0.739567099661973;
   fWeightMatrix0to1[11][8] = 2.08097307321227;
   fWeightMatrix0to1[12][8] = -0.0539591109171772;
   fWeightMatrix0to1[13][8] = -0.0299765284942142;
   fWeightMatrix0to1[0][9] = -6.44268416665451;
   fWeightMatrix0to1[1][9] = -0.283174460182269;
   fWeightMatrix0to1[2][9] = -2.22423110700008;
   fWeightMatrix0to1[3][9] = 1.68934343667995;
   fWeightMatrix0to1[4][9] = 4.80467562804278;
   fWeightMatrix0to1[5][9] = -5.92041407788271;
   fWeightMatrix0to1[6][9] = 0.681097177101926;
   fWeightMatrix0to1[7][9] = -1.48020440345897;
   fWeightMatrix0to1[8][9] = 0.188683745790761;
   fWeightMatrix0to1[9][9] = 1.02277122973201;
   fWeightMatrix0to1[10][9] = 2.54007461557239;
   fWeightMatrix0to1[11][9] = -1.5866202705319;
   fWeightMatrix0to1[12][9] = 1.14971409205799;
   fWeightMatrix0to1[13][9] = 1.53456180520953;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 6.06251715492741;
   fWeightMatrix1to2[0][1] = 0.578484863903585;
   fWeightMatrix1to2[0][2] = -2.40314844579589;
   fWeightMatrix1to2[0][3] = -3.22065396942928;
   fWeightMatrix1to2[0][4] = -3.63355751686041;
   fWeightMatrix1to2[0][5] = 4.88652540822496;
   fWeightMatrix1to2[0][6] = 2.41606148041795;
   fWeightMatrix1to2[0][7] = 0.56422666810995;
   fWeightMatrix1to2[0][8] = -2.97835745832472;
   fWeightMatrix1to2[0][9] = 2.84144479773592;
   fWeightMatrix1to2[0][10] = -2.05775472059426;
   fWeightMatrix1to2[0][11] = 0.378873062823657;
   fWeightMatrix1to2[0][12] = 2.12574770255667;
   fWeightMatrix1to2[0][13] = 0.660015185929276;
   fWeightMatrix1to2[0][14] = 0.608472578829011;
}

inline double ReadMLP_PIMU_Plus::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)9) {
      std::cout << "Input vector needs to be of size " << 9 << std::endl;
      return 0;
   }

   std::array<double, 15> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<14; o++) {
      std::array<double, 10> buffer; // no need to initialise
      for (int i = 0; i<10 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][9];
      for (int i=0; i<10; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<14; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 15> buffer; // no need to initialise
      for (int i=0; i<15; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<15; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLP_PIMU_Plus::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP_PIMU_Plus::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP_PIMU_Plus::Clear()
{
}
inline double ReadMLP_PIMU_Plus::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Plus::InitTransform_1()
{
   double fMin_1[3][9];
   double fMax_1[3][9];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 1.13870537281;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 0.752225577831;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 1.13870537281;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.0325273983181;
   fMax_1[0][1] = 999;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 0.00257715024054;
   fMax_1[1][1] = 999;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 0.00257715024054;
   fMax_1[2][1] = 999;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 1;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 1;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 1;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 15;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 4;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 15;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 45;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 10;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 45;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 32;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 8;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 32;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 34;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 17;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 34;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 21;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 9;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 21;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 19;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 19;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Plus::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Plus::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Plus::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
