// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.36/04       [402436]
Creator        : apollo
Date           : Fri Feb 27 16:40:11 2026
Host           : Darwin Mac-1759393079197.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64 x86_64
Dir            : /Users/apollo/Work/cpp_analysis/ml_models/project_hylax/root_tmva/single_track_tmva/minustrack
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
FCAL_eoverp_9                 FCAL_eoverp_9                 FCAL_eoverp_9                 FCAL_eoverp_9                                                   'F'    [0,2.7707593441]
FCAL_doca_9                   FCAL_doca_9                   FCAL_doca_9                   FCAL_doca_9                                                     'F'    [0.0325273983181,999]
FCALShower_E1E9_9             FCALShower_E1E9_9             FCALShower_E1E9_9             FCALShower_E1E9_9                                               'F'    [0,1]
FCAL_blocks_n_9               FCAL_blocks_n_9               FCAL_blocks_n_9               FCAL_blocks_n_9                                                 'F'    [0,15]
Chamber1MatchedHits9          Chamber1MatchedHits9          Chamber1MatchedHits9          Chamber1MatchedHits9                                            'F'    [0,79]
Chamber2MatchedHits9          Chamber2MatchedHits9          Chamber2MatchedHits9          Chamber2MatchedHits9                                            'F'    [0,20]
Chamber3MatchedHits9          Chamber3MatchedHits9          Chamber3MatchedHits9          Chamber3MatchedHits9                                            'F'    [0,24]
Chamber4MatchedHits9          Chamber4MatchedHits9          Chamber4MatchedHits9          Chamber4MatchedHits9                                            'F'    [0,46]
Chamber5MatchedHits9          Chamber5MatchedHits9          Chamber5MatchedHits9          Chamber5MatchedHits9                                            'F'    [0,19]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_PIMU_Minus : public IClassifierReader {

 public:

   // constructor
   ReadMLP_PIMU_Minus( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP_PIMU_Minus" ),
        fNvars( 9 )
   {
      // the training input variables
      const char* inputVars[] = { "FCAL_eoverp_9", "FCAL_doca_9", "FCALShower_E1E9_9", "FCAL_blocks_n_9", "Chamber1MatchedHits9", "Chamber2MatchedHits9", "Chamber3MatchedHits9", "Chamber4MatchedHits9", "Chamber5MatchedHits9" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_PIMU_Minus() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fOff_1[3][9];
   double fScal_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   double fWeightMatrix0to1[15][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

};

inline void ReadMLP_PIMU_Minus::Initialize()
{
   // build network structure
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.37889025351429;
   fWeightMatrix0to1[1][0] = 1.96908329520455;
   fWeightMatrix0to1[2][0] = 1.28665802977729;
   fWeightMatrix0to1[3][0] = 3.27399944967857;
   fWeightMatrix0to1[4][0] = -1.53880540597333;
   fWeightMatrix0to1[5][0] = -3.37094446166054;
   fWeightMatrix0to1[6][0] = -1.07374423007493;
   fWeightMatrix0to1[7][0] = 2.16121347580841;
   fWeightMatrix0to1[8][0] = -1.25911012299673;
   fWeightMatrix0to1[9][0] = -0.985632473414702;
   fWeightMatrix0to1[10][0] = -1.02766653405699;
   fWeightMatrix0to1[11][0] = -0.488727709697885;
   fWeightMatrix0to1[12][0] = -1.58304869508108;
   fWeightMatrix0to1[13][0] = -0.44827578547058;
   fWeightMatrix0to1[0][1] = -0.423971089620786;
   fWeightMatrix0to1[1][1] = -0.304222423932638;
   fWeightMatrix0to1[2][1] = 0.0676489560656039;
   fWeightMatrix0to1[3][1] = 0.735945215389198;
   fWeightMatrix0to1[4][1] = -0.646645562350616;
   fWeightMatrix0to1[5][1] = 6.8350209729193;
   fWeightMatrix0to1[6][1] = -0.61258557067082;
   fWeightMatrix0to1[7][1] = -0.48029270782041;
   fWeightMatrix0to1[8][1] = 1.94915320727873;
   fWeightMatrix0to1[9][1] = -0.920479986561133;
   fWeightMatrix0to1[10][1] = -0.869363249488143;
   fWeightMatrix0to1[11][1] = -0.305936996963954;
   fWeightMatrix0to1[12][1] = 0.8215096445709;
   fWeightMatrix0to1[13][1] = -1.08167655491422;
   fWeightMatrix0to1[0][2] = -0.534355114379916;
   fWeightMatrix0to1[1][2] = 0.0887727820824907;
   fWeightMatrix0to1[2][2] = 0.391451287995132;
   fWeightMatrix0to1[3][2] = -0.14682758136832;
   fWeightMatrix0to1[4][2] = -0.197632010435688;
   fWeightMatrix0to1[5][2] = -0.00404931565160375;
   fWeightMatrix0to1[6][2] = 0.374343125596495;
   fWeightMatrix0to1[7][2] = -0.369198874521754;
   fWeightMatrix0to1[8][2] = -1.80269132606507;
   fWeightMatrix0to1[9][2] = 1.82415234989544;
   fWeightMatrix0to1[10][2] = -0.635652040994974;
   fWeightMatrix0to1[11][2] = 1.13993906362412;
   fWeightMatrix0to1[12][2] = 1.26266768505387;
   fWeightMatrix0to1[13][2] = 0.863646277497985;
   fWeightMatrix0to1[0][3] = 0.916765269609374;
   fWeightMatrix0to1[1][3] = 2.33727019020312;
   fWeightMatrix0to1[2][3] = -0.510859655219558;
   fWeightMatrix0to1[3][3] = -1.41953449692011;
   fWeightMatrix0to1[4][3] = -0.0501317057320157;
   fWeightMatrix0to1[5][3] = -0.740924958106284;
   fWeightMatrix0to1[6][3] = 1.30878728394034;
   fWeightMatrix0to1[7][3] = 1.53829891697635;
   fWeightMatrix0to1[8][3] = 1.29669553311079;
   fWeightMatrix0to1[9][3] = 1.4978899250474;
   fWeightMatrix0to1[10][3] = -1.25137471872367;
   fWeightMatrix0to1[11][3] = 1.27838488344549;
   fWeightMatrix0to1[12][3] = -1.83622230385729;
   fWeightMatrix0to1[13][3] = -0.907589104797573;
   fWeightMatrix0to1[0][4] = 0.0607069378089446;
   fWeightMatrix0to1[1][4] = -2.21414855650386;
   fWeightMatrix0to1[2][4] = 1.86434511988604;
   fWeightMatrix0to1[3][4] = 0.721202689100852;
   fWeightMatrix0to1[4][4] = -5.02597892774671;
   fWeightMatrix0to1[5][4] = 3.1593601186251;
   fWeightMatrix0to1[6][4] = -0.599789869574293;
   fWeightMatrix0to1[7][4] = 0.947509167351256;
   fWeightMatrix0to1[8][4] = 2.06041811646648;
   fWeightMatrix0to1[9][4] = -0.249168531926777;
   fWeightMatrix0to1[10][4] = -0.109435393102815;
   fWeightMatrix0to1[11][4] = -1.2872825040784;
   fWeightMatrix0to1[12][4] = 0.0972499309101064;
   fWeightMatrix0to1[13][4] = -0.841512032968001;
   fWeightMatrix0to1[0][5] = 3.6922829719603;
   fWeightMatrix0to1[1][5] = -2.9093855832662;
   fWeightMatrix0to1[2][5] = 0.865643226652254;
   fWeightMatrix0to1[3][5] = -1.62222674855428;
   fWeightMatrix0to1[4][5] = 4.0356035443881;
   fWeightMatrix0to1[5][5] = 0.121102534049904;
   fWeightMatrix0to1[6][5] = -1.74180896986764;
   fWeightMatrix0to1[7][5] = -1.62404321997881;
   fWeightMatrix0to1[8][5] = 0.69569470529061;
   fWeightMatrix0to1[9][5] = 1.07722582849422;
   fWeightMatrix0to1[10][5] = 5.05789312853514;
   fWeightMatrix0to1[11][5] = 0.595951096319563;
   fWeightMatrix0to1[12][5] = 0.43580815048982;
   fWeightMatrix0to1[13][5] = -0.805460714750516;
   fWeightMatrix0to1[0][6] = -0.981607059640246;
   fWeightMatrix0to1[1][6] = -2.52027800629761;
   fWeightMatrix0to1[2][6] = 1.38674608677242;
   fWeightMatrix0to1[3][6] = -4.86389600233526;
   fWeightMatrix0to1[4][6] = -0.486042076318036;
   fWeightMatrix0to1[5][6] = -6.53531981427188;
   fWeightMatrix0to1[6][6] = -0.463613440473353;
   fWeightMatrix0to1[7][6] = 0.144898532154779;
   fWeightMatrix0to1[8][6] = 1.43191680069419;
   fWeightMatrix0to1[9][6] = -1.73508093335636;
   fWeightMatrix0to1[10][6] = 0.868580859593348;
   fWeightMatrix0to1[11][6] = 1.59654285308368;
   fWeightMatrix0to1[12][6] = -1.43816635389652;
   fWeightMatrix0to1[13][6] = -1.52224237844751;
   fWeightMatrix0to1[0][7] = -4.22077686477166;
   fWeightMatrix0to1[1][7] = -0.39265234924;
   fWeightMatrix0to1[2][7] = -1.39400975133663;
   fWeightMatrix0to1[3][7] = -1.92613998508653;
   fWeightMatrix0to1[4][7] = 4.68110856038874;
   fWeightMatrix0to1[5][7] = 0.0121390314198846;
   fWeightMatrix0to1[6][7] = -1.43263604519335;
   fWeightMatrix0to1[7][7] = 1.61285884742895;
   fWeightMatrix0to1[8][7] = -0.634938434284453;
   fWeightMatrix0to1[9][7] = -0.856042716643459;
   fWeightMatrix0to1[10][7] = 0.982233177904345;
   fWeightMatrix0to1[11][7] = 0.258153539021037;
   fWeightMatrix0to1[12][7] = -2.13687905724103;
   fWeightMatrix0to1[13][7] = 0.263575110039073;
   fWeightMatrix0to1[0][8] = 0.228952811191222;
   fWeightMatrix0to1[1][8] = 4.30132246213174;
   fWeightMatrix0to1[2][8] = -0.832126054629606;
   fWeightMatrix0to1[3][8] = 5.76914916367854;
   fWeightMatrix0to1[4][8] = 4.45029588433315;
   fWeightMatrix0to1[5][8] = -7.58819249058803;
   fWeightMatrix0to1[6][8] = 0.493019705599348;
   fWeightMatrix0to1[7][8] = -0.808721608635638;
   fWeightMatrix0to1[8][8] = -1.21857018044183;
   fWeightMatrix0to1[9][8] = -0.0519679916928464;
   fWeightMatrix0to1[10][8] = -1.35155059695013;
   fWeightMatrix0to1[11][8] = 1.78379137857668;
   fWeightMatrix0to1[12][8] = 0.0831613650765981;
   fWeightMatrix0to1[13][8] = -0.0278445988228567;
   fWeightMatrix0to1[0][9] = -2.65682989118687;
   fWeightMatrix0to1[1][9] = -0.923940281945664;
   fWeightMatrix0to1[2][9] = -2.28190100895874;
   fWeightMatrix0to1[3][9] = 2.05725498430248;
   fWeightMatrix0to1[4][9] = 5.79846980027524;
   fWeightMatrix0to1[5][9] = -7.37357735154487;
   fWeightMatrix0to1[6][9] = 0.986826657559619;
   fWeightMatrix0to1[7][9] = -1.70784410905823;
   fWeightMatrix0to1[8][9] = -0.191990161238303;
   fWeightMatrix0to1[9][9] = 1.05392291181282;
   fWeightMatrix0to1[10][9] = 3.37818461851436;
   fWeightMatrix0to1[11][9] = -1.80076906397931;
   fWeightMatrix0to1[12][9] = 1.04041264495425;
   fWeightMatrix0to1[13][9] = 1.53251427763701;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 3.86409921181508;
   fWeightMatrix1to2[0][1] = 3.21782550307991;
   fWeightMatrix1to2[0][2] = -2.1851229104872;
   fWeightMatrix1to2[0][3] = -4.37918287280343;
   fWeightMatrix1to2[0][4] = -5.03188615235726;
   fWeightMatrix1to2[0][5] = 5.79672679512567;
   fWeightMatrix1to2[0][6] = 2.17229099646336;
   fWeightMatrix1to2[0][7] = -1.12668222334047;
   fWeightMatrix1to2[0][8] = -1.70311105044076;
   fWeightMatrix1to2[0][9] = 2.7536464793688;
   fWeightMatrix1to2[0][10] = -2.6223326478558;
   fWeightMatrix1to2[0][11] = -0.442279230258592;
   fWeightMatrix1to2[0][12] = 2.41167551858751;
   fWeightMatrix1to2[0][13] = 0.519411499972746;
   fWeightMatrix1to2[0][14] = 0.465310888939004;
}

inline double ReadMLP_PIMU_Minus::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)9) {
      std::cout << "Input vector needs to be of size " << 9 << std::endl;
      return 0;
   }

   std::array<double, 15> fWeights1 {{}};
   std::array<double, 1> fWeights2 {{}};
   fWeights1.back() = 1.;

   // layer 0 to 1
   for (int o=0; o<14; o++) {
      std::array<double, 10> buffer; // no need to initialise
      for (int i = 0; i<10 - 1; i++) {
         buffer[i] = fWeightMatrix0to1[o][i] * inputValues[i];
      } // loop over i
      buffer.back() = fWeightMatrix0to1[o][9];
      for (int i=0; i<10; i++) {
         fWeights1[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<14; o++) {
      fWeights1[o] = ActivationFnc(fWeights1[o]);
   } // loop over o
   // layer 1 to 2
   for (int o=0; o<1; o++) {
      std::array<double, 15> buffer; // no need to initialise
      for (int i=0; i<15; i++) {
         buffer[i] = fWeightMatrix1to2[o][i] * fWeights1[i];
      } // loop over i
      for (int i=0; i<15; i++) {
         fWeights2[o] += buffer[i];
      } // loop over i
    } // loop over o
   for (int o=0; o<1; o++) {
      fWeights2[o] = OutputActivationFnc(fWeights2[o]);
   } // loop over o

   return fWeights2[0];
}

double ReadMLP_PIMU_Minus::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP_PIMU_Minus::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}

// Clean up
inline void ReadMLP_PIMU_Minus::Clear()
{
}
inline double ReadMLP_PIMU_Minus::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         std::vector<double> iV(inputValues);
         Transform( iV, -1 );
         retval = GetMvaValue__( iV );
   }

   return retval;
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Minus::InitTransform_1()
{
   double fMin_1[3][9];
   double fMax_1[3][9];
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 2.7707593441;
   fScal_1[0][0] = 2.0/(fMax_1[0][0]-fMin_1[0][0]);
   fOff_1[0][0] = fMin_1[0][0]*fScal_1[0][0]+1.;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 0.765402257442;
   fScal_1[1][0] = 2.0/(fMax_1[1][0]-fMin_1[1][0]);
   fOff_1[1][0] = fMin_1[1][0]*fScal_1[1][0]+1.;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 2.7707593441;
   fScal_1[2][0] = 2.0/(fMax_1[2][0]-fMin_1[2][0]);
   fOff_1[2][0] = fMin_1[2][0]*fScal_1[2][0]+1.;
   fMin_1[0][1] = 0.0325273983181;
   fMax_1[0][1] = 999;
   fScal_1[0][1] = 2.0/(fMax_1[0][1]-fMin_1[0][1]);
   fOff_1[0][1] = fMin_1[0][1]*fScal_1[0][1]+1.;
   fMin_1[1][1] = 0.0674363598228;
   fMax_1[1][1] = 999;
   fScal_1[1][1] = 2.0/(fMax_1[1][1]-fMin_1[1][1]);
   fOff_1[1][1] = fMin_1[1][1]*fScal_1[1][1]+1.;
   fMin_1[2][1] = 0.0325273983181;
   fMax_1[2][1] = 999;
   fScal_1[2][1] = 2.0/(fMax_1[2][1]-fMin_1[2][1]);
   fOff_1[2][1] = fMin_1[2][1]*fScal_1[2][1]+1.;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 1;
   fScal_1[0][2] = 2.0/(fMax_1[0][2]-fMin_1[0][2]);
   fOff_1[0][2] = fMin_1[0][2]*fScal_1[0][2]+1.;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 1;
   fScal_1[1][2] = 2.0/(fMax_1[1][2]-fMin_1[1][2]);
   fOff_1[1][2] = fMin_1[1][2]*fScal_1[1][2]+1.;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 1;
   fScal_1[2][2] = 2.0/(fMax_1[2][2]-fMin_1[2][2]);
   fOff_1[2][2] = fMin_1[2][2]*fScal_1[2][2]+1.;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 15;
   fScal_1[0][3] = 2.0/(fMax_1[0][3]-fMin_1[0][3]);
   fOff_1[0][3] = fMin_1[0][3]*fScal_1[0][3]+1.;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 5;
   fScal_1[1][3] = 2.0/(fMax_1[1][3]-fMin_1[1][3]);
   fOff_1[1][3] = fMin_1[1][3]*fScal_1[1][3]+1.;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 15;
   fScal_1[2][3] = 2.0/(fMax_1[2][3]-fMin_1[2][3]);
   fOff_1[2][3] = fMin_1[2][3]*fScal_1[2][3]+1.;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 79;
   fScal_1[0][4] = 2.0/(fMax_1[0][4]-fMin_1[0][4]);
   fOff_1[0][4] = fMin_1[0][4]*fScal_1[0][4]+1.;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 10;
   fScal_1[1][4] = 2.0/(fMax_1[1][4]-fMin_1[1][4]);
   fOff_1[1][4] = fMin_1[1][4]*fScal_1[1][4]+1.;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 79;
   fScal_1[2][4] = 2.0/(fMax_1[2][4]-fMin_1[2][4]);
   fOff_1[2][4] = fMin_1[2][4]*fScal_1[2][4]+1.;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 20;
   fScal_1[0][5] = 2.0/(fMax_1[0][5]-fMin_1[0][5]);
   fOff_1[0][5] = fMin_1[0][5]*fScal_1[0][5]+1.;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 8;
   fScal_1[1][5] = 2.0/(fMax_1[1][5]-fMin_1[1][5]);
   fOff_1[1][5] = fMin_1[1][5]*fScal_1[1][5]+1.;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 20;
   fScal_1[2][5] = 2.0/(fMax_1[2][5]-fMin_1[2][5]);
   fOff_1[2][5] = fMin_1[2][5]*fScal_1[2][5]+1.;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 24;
   fScal_1[0][6] = 2.0/(fMax_1[0][6]-fMin_1[0][6]);
   fOff_1[0][6] = fMin_1[0][6]*fScal_1[0][6]+1.;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 16;
   fScal_1[1][6] = 2.0/(fMax_1[1][6]-fMin_1[1][6]);
   fOff_1[1][6] = fMin_1[1][6]*fScal_1[1][6]+1.;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 24;
   fScal_1[2][6] = 2.0/(fMax_1[2][6]-fMin_1[2][6]);
   fOff_1[2][6] = fMin_1[2][6]*fScal_1[2][6]+1.;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 46;
   fScal_1[0][7] = 2.0/(fMax_1[0][7]-fMin_1[0][7]);
   fOff_1[0][7] = fMin_1[0][7]*fScal_1[0][7]+1.;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 15;
   fScal_1[1][7] = 2.0/(fMax_1[1][7]-fMin_1[1][7]);
   fOff_1[1][7] = fMin_1[1][7]*fScal_1[1][7]+1.;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 46;
   fScal_1[2][7] = 2.0/(fMax_1[2][7]-fMin_1[2][7]);
   fOff_1[2][7] = fMin_1[2][7]*fScal_1[2][7]+1.;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 19;
   fScal_1[0][8] = 2.0/(fMax_1[0][8]-fMin_1[0][8]);
   fOff_1[0][8] = fMin_1[0][8]*fScal_1[0][8]+1.;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 9;
   fScal_1[1][8] = 2.0/(fMax_1[1][8]-fMin_1[1][8]);
   fOff_1[1][8] = fMin_1[1][8]*fScal_1[1][8]+1.;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 19;
   fScal_1[2][8] = 2.0/(fMax_1[2][8]-fMin_1[2][8]);
   fOff_1[2][8] = fMin_1[2][8]*fScal_1[2][8]+1.;
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Minus::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) {
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   }
   if ( indicesPut.empty() ) {
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   }

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fOff_1[cls][ivar];
      double scale  = fScal_1[cls][ivar];
      iv[indicesPut.at(ivar)] = scale*dv[ivar]-offset;
   }
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Minus::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_PIMU_Minus::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
