
import sbms

Import('*')

# update this when plugins are added

subdirs = ['BCAL_attenlength_gainratio','BCAL_gainmatrix','BCAL_TDC_Timing','CDC_amp','HLDetectorTiming','TAGH_timewalk','CDC_TimeToDistance','PS_timing','PSC_TW','PS_E_calib','st_tw_corr_auto','ST_Propagation_Time','ST_Tresolution','TAGM_TW','TOF_calib','FCALLEDTree','cal_cal','fcal_led','PStagstudy','FdcTimeToDistance']

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

optdirs = ['FCALpedestals','FCALpulsepeak','FCAL_TimingOffsets','FCAL_Pi0TOF']
optdirs.extend(['BCAL_saturation','BCAL_SiPM_saturation','FCAL_LED_shifts','FCAL_TimingOffsets_Primex'])

sbms.OptionallyBuild(env, optdirs)
