
import sbms

Import('*')

# Default targets (always built)
subdirs = ['danarest', 'evio_writer', 'evio-hddm']
subdirs.extend(['pi0bcalskim', 'trackeff_missing','ps_skim', 'trigger_skims', 'exclusivepi0skim', 'randomtrigger_skim', 'pi0fcaltofskim' ])
subdirs.extend(['omega_skim', 'syncskim'])

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets
optdirs = [ '2trackskim', 'bigevents_skim', 'coherent_peak_skim' , 'twogamma_fcal_skim' ]
optdirs.extend(['pi0fcalskim', 'single_neutral_skim','compton_neutral_skim' ])
optdirs.extend(['eta2g_primexd_skim','eta6g_primexd_skim','etapi0_primexd_skim' ])
optdirs.extend(['cdcbcal_skim', 'cdc_goodtrack_skim'])
optdirs.extend(['run_summary', 'track_skimmer' ])
optdirs.extend(['merge_rawevents', 'syncskim'])
optdirs.extend(['Pi0Finder', 'EventTagPi0','cal_high_energy_skim', 'phi_skim', 'npp_skim', 'cpp_skim'])  
optdirs.extend(['cdc_amp_t','cdc_echo','cdc_emu','cdc_scan', 'fmwpc_scan', 'epem_ml_skim'])
sbms.OptionallyBuild(env, optdirs)
